name: Docker Build and Push

on:
  push:
    branches:
      - josyy

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run pytest
      run: |
        docker build -t jossyfresh2002425/fizzbuzz-image .
        docker run jossyfresh2002425/fizzbuzz-image pytest

    - name: Log in to Docker Hub
      run: echo "dckr_pat_I7VWrvkLc3Z_uQOp3w-rvpHueEQ" | docker login -u jossyfresh2002425 --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push jossyfresh2002425/dockerlesson-image
